---

- name: 'gitlab : create gitlab directories'
  become: true
  file:
    path: '{{ gitlab_dir }}/{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0550
  loop:
    - ""
    - "data"
    - "logs"
    - "config"

- name: "gitlab : build gitlab docker-compose"
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ gitlab_dir }}/docker-compose.yml"

- name: 'gitlab : deploy gitlab stack from a compose file'
  docker_stack:
    state: present
    name: "{{ gitlab_stack_name }}"
    compose:
      - "{{ gitlab_dir }}/docker-compose.yml"